version: '3.8'
services:
  service1:
    container_name: fortune-swarm_service1
    image: bbkirkby99/fortune-service1:${app_version}
    build: ./service1
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      app_version: ${app_version}
    deploy:
      replicas: ${replicas}
  service2:
    container_name: fortune-swarm_service2
    image: bbkirkby99/fortune-service2:${app_version}
    build: ./service2
    deploy:
      replicas: ${replicas}
    environment:
      app_version: ${app_version}
  service3:
    container_name: fortune-swarm_service3
    image: bbkirkby99/fortune2-service3:${app_version}
    build: ./service3
    deploy:
      replicas: ${replicas}
    environment:
      app_version: ${app_version}
  service4:
    container_name: fortune-swarm_service4
    image: bbkirkby99/fortune2-service4:${app_version}
    build: ./service4
    deploy:
      replicas: ${replicas}
    environment:
      app_version: ${app_version}
