version: '3.8'
services:
  service1:
    container_name: fortune-swarm_service1:${app_version}
    image: bbkirkby99/fortune-service1
    build: ./service1
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      app_version: ${app_version}
  service2:
    container_name: fortune-swarm_service2:${app_version}
    build: ./service2
    image: bbkirkby99/fortune-service2
    environment:
      app_version: ${app_version}
  service3:
    container_name: fortune-swarm_service3:${app_version}
    build: ./service3
    image: bbkirkby99/fortune-service3
    environment:
      app_version: ${app_version}
  service4:
    container_name: fortune-swarm_service4:${app_version}
    build: ./service4
    image: bbkirkby99/fortune-service4
    environment:
      app_version: ${app_version}
