---
    - name: Ensure jenkins is part of docker group
      user:
        name: jenkins
        groups: docker
        shell: /bin/bash
        append: true
    - name: Init swarm
      community.general.docker_swarm:
        state: present
        register: swinfo