---
  - name: Add worker to manager node
    community.general.docker_swarm:
      state: join
      advertise_addr: "{{ inventory_hostname }}"
      join_token: "{{ hostvars['swarm-mgr']['swinfo']['swarm_facts']['JoinTokens']['Worker'] }}"
      remote_addrs: [ 'swarm-mgr:2377' ]