---
    - name: Install various docker dependencies
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3
        - python3-pip
        - python-setuptools
      state: latest
      update_cache: yes
      tags: docker-install
  - name: Get Docker official GPG Key
    apt-key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags: docker-install
  - name: Add docker packages to repo
    apt_repository: 
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    tags: docker-install

  - name: Install Docker/Docker Engine
    apt:
      name: docker-ce
      state: latest
      update_cache: true
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: Pip docker executable
    pip:
      executable: pip3
      name: docker