---
  - name: Setup nginx load balancer as sudo
    become: true
    hosts: nginx
    roles:
      - nginx
  - name: Init docker swarm as sudo
    become: true
    hosts: managers
    roles:
      - docker
      - docker-swarm-init
  - name: Add worker(s) to swarm as sudo
    become: true
    hosts: workers
    roles:
      - docker
      - docker-swarm-wrk